# Generated by Django 4.1.4 on 2026-03-10 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def seed_academic_data(apps, schema_editor):
    Department = apps.get_model("core", "Department")
    Major = apps.get_model("core", "Major")
    Minor = apps.get_model("core", "Minor")

    departments = [
        "Computer Science",
        "Electrical Science",
        "Architecture",
    ]

    for dept_name in departments:
        Department.objects.get_or_create(name=dept_name)

    major_seed = {
        "Computer Science": ["Software Engineering", "Data Science"],
        "Electrical Science": ["Embedded Systems", "Power Systems"],
        "Architecture": ["Urban Design", "Sustainable Architecture"],
    }

    minor_seed = {
        "Computer Science": ["Cybersecurity", "Human-Computer Interaction"],
        "Electrical Science": ["Robotics", "Internet of Things"],
        "Architecture": ["Landscape Design", "History of Architecture"],
    }

    for dept_name, majors in major_seed.items():
        dept = Department.objects.get(name=dept_name)
        for major in majors:
            Major.objects.get_or_create(name=major, defaults={"department": dept})

    for dept_name, minors in minor_seed.items():
        dept = Department.objects.get(name=dept_name)
        for minor in minors:
            Minor.objects.get_or_create(name=minor, defaults={"department": dept})


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_waitlistentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subjecttag",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("bachelors", "Bachelor"),
                    ("masters", "Masters"),
                    ("phd", "Doctorate/PhD"),
                ],
                default="bachelors",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("bachelors", "Bachelor"),
                    ("masters", "Masters"),
                    ("phd", "Doctorate/PhD"),
                ],
                default="bachelors",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Minor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="minors",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="majors",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("absent", "Absent")],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("marked_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="core.studysession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Attendance",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="major",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.major",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="minor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.minor",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("session", "user"), name="unique_attendance_entry"
            ),
        ),
        migrations.RunPython(seed_academic_data, migrations.RunPython.noop),
    ]
