# Generated by Django 4.1.4 on 2026-03-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_department_userprofile_onboarding_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_faculty",
            field=models.BooleanField(default=False),
        ),
    ]
