# Generated by Django 4.1.4 on 2026-03-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_userprofile_is_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="visible_departments",
            field=models.ManyToManyField(
                blank=True, related_name="visible_sessions", to="core.department"
            ),
        ),
    ]
