# Generated by Django 4.1.4 on 2026-03-10 23:59

from django.db import migrations
from django.utils.text import slugify


def seed_subjects(apps, schema_editor):
    SubjectTag = apps.get_model("core", "SubjectTag")
    Department = apps.get_model("core", "Department")

    dept_names = ["Computer Science", "Electrical Science", "Architecture"]
    departments = [Department.objects.get_or_create(name=name)[0] for name in dept_names]

    dept_lookup = {d.name: d for d in departments}
    dept_cycle = [d.name for d in departments]

    keyword_map = {
        "Computer Science": [
            "computer", "software", "data", "ai", "machine", "database",
            "network", "cyber", "web", "mobile", "information", "algorithm",
            "systems", "programming",
        ],
        "Electrical Science": [
            "electrical", "circuit", "signal", "embedded", "power", "electronics",
            "hardware", "robotics", "iot", "communication", "control",
        ],
        "Architecture": [
            "architecture", "design", "urban", "building", "structural",
            "landscape", "planning",
        ],
    }

    # Ensure existing subjects have departments set
    fallback_index = 0
    for subject in SubjectTag.objects.filter(department=""):
        name_lower = subject.name.lower()
        assigned = None
        for dept, keywords in keyword_map.items():
            if any(k in name_lower for k in keywords):
                assigned = dept
                break
        if not assigned:
            assigned = dept_cycle[fallback_index % len(dept_cycle)]
            fallback_index += 1
        subject.department = assigned
        subject.save(update_fields=["department"])

    seed = {
        "Computer Science": {
            "bachelors": ["Data Structures", "Algorithms", "Operating Systems"],
            "masters": ["Advanced Algorithms", "Distributed Systems", "Machine Learning"],
            "phd": ["Research Methods", "Advanced Systems", "AI Research"],
        },
        "Electrical Science": {
            "bachelors": ["Circuits", "Signals & Systems", "Digital Electronics"],
            "masters": ["Advanced Signals", "Embedded Systems", "Power Electronics"],
            "phd": ["Research Methods", "Advanced Circuits", "Signal Processing Research"],
        },
        "Architecture": {
            "bachelors": ["Design Studio", "Structural Systems", "Architectural History"],
            "masters": ["Advanced Design", "Urban Systems", "Sustainable Architecture"],
            "phd": ["Research Methods", "Architectural Theory", "Design Research"],
        },
    }

    for dept_name, subjects_by_level in seed.items():
        for level, subjects in subjects_by_level.items():
            for name in subjects:
                subject, created = SubjectTag.objects.get_or_create(
                    name=name,
                    education_level=level,
                    defaults={
                        "slug": slugify(f"{name}-{dept_name}-{level}"),
                        "department": dept_name,
                    },
                )
                if not created and not subject.department:
                    subject.department = dept_name
                    subject.save(update_fields=["department"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_studysession_visible_departments"),
    ]

    operations = [
        migrations.RunPython(seed_subjects, migrations.RunPython.noop),
    ]
