# Generated by Django 5.2.5 on 2026-04-30 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_seed_subjecttags_by_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studynote",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="subjecttag",
            options={"ordering": ["department", "name"]},
        ),
        migrations.AddField(
            model_name="studynote",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="core.studysession",
            ),
        ),
        migrations.AddField(
            model_name="studynote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subjecttag",
            name="name",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="subjecttag",
            name="slug",
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "created_at"], name="core_messag_session_567bd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studynote",
            index=models.Index(
                fields=["session", "user"], name="core_studyn_session_7d594e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(
                fields=["owner", "start_time"], name="core_studys_owner_i_d396bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjecttag",
            index=models.Index(
                fields=["education_level", "department"],
                name="core_subjec_educati_f2f19a_idx",
            ),
        ),
    ]
